"""Add missing user profile fields

Revision ID: 2a65a6fcfa0c
Revises: f7f977f06284
Create Date: 2026-01-16 19:10:34.777068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a65a6fcfa0c'
down_revision: Union[str, Sequence[str], None] = 'f7f977f06284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circulars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('downloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('note_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('note_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('note_id', sa.UUID(), nullable=True),
    sa.Column('vote_type', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notes', sa.Column('category', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('vote_count', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('notes', sa.Column('rating_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mobile_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('semester', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('cgpa', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('sgpa', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('target_cgpa', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('study_hours', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'study_hours')
    op.drop_column('users', 'target_cgpa')
    op.drop_column('users', 'sgpa')
    op.drop_column('users', 'cgpa')
    op.drop_column('users', 'semester')
    op.drop_column('users', 'mobile_number')
    op.drop_column('users', 'full_name')
    op.drop_column('notes', 'rating_count')
    op.drop_column('notes', 'rating')
    op.drop_column('notes', 'vote_count')
    op.drop_column('notes', 'year')
    op.drop_column('notes', 'category')
    op.drop_table('votes')
    op.drop_table('reviews')
    op.drop_table('downloads')
    op.drop_table('circulars')
    # ### end Alembic commands ###
